name: Run Watcher

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Shanghai"
      MODE: "prod"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run main
        run: |
          python main.py run --mode ${{ env.MODE }}

      - name: Setup var
        id: vars
        run: |
          content=$(cat mail.md)
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$content" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Setup GIT user
        uses: fregante/setup-git-user@v1

      - name: Create an issue for msg
        if: ${{ steps.vars.outputs.content != '' }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MSG: ${{ steps.vars.outputs.content }}
        with:
          filename: .github/issue-template.md
